### ISSUE TITLE
question about linking logic

### ISSUE THREAD

**Issue by masato-io** [websiddu/sync-to-slides#4]
Hi, I found this plugin was the missing part of my company's design workflow and this is incredibly helpful for us. Thank you so much for creating this project 👏👏👏

Once question I had was how this plugin is creating a link between sketch artboard <--> google slide? 

Reason why I'm asking this question is that I realized sometimes when I do:

1. I push artboards to google slides
2. make local modification to artboard files
3. I re-push artboards to google slides

at 3, most of the times re-pushing simply update the existing slides as expected, but sometimes it creates new slides instead of updating and I was wondering what might causes that behavior. Your input would be really appreciated!

**Comment by websiddu** [comment]
I'm glad this is helping your company. 
Here is how the sync happens, So when you sync for the first time, it creates a slide with the artboard id (which is a unique ID generated by sketch) so the next time you sync, it will find the slide with the id and update those items otherwise create a new one. 

If you delete the artboard or make a copy the id's will be different and it will create a new slide.

**Comment by masato-io** [comment]
okay got it, that totally makes sense. Thank you for your response @websiddu!
